### ISSUE TITLE
plotDecontXMarkerPercentage omit celltype when it has two clusters concatenated

### ISSUE THREAD

**Issue by makloufg** [campbio/celda#323]
Hi!

First of all: thanks for the super useful package and also for making a well-explained vignette, which makes it easy to implement :)
I'm trying to use the function plotDecontXMarkerPercentage, but when I put a list with some cell types with more than one cluster in 'groupClusters' parameter I receive the following error:

**STATS is longer than the extent of 'dim(x)[MARGIN]'**

Besides that, the cell type that has more than one cluster is omitted from my plot. When I choose only one cluster the cell type is not omitted.

My code:

`
markers <- list(Myeloid_Markers = c('CD68', 'LYZ', 'AIF1'),
                pDC_Markers = c('LILRA4', "IRF7"),
                Lymphocytes_Markers = c("CD3D", "CD3E",'GNLY', 'NKG7', "CD79A", 
 "MS4A1"),
                Malignant_Markers = c("EPCAM","PAX8"),
                EC_Markers = c("CLDN5", "PECAM1", "VWF"),
                Fibroblasts_Markers = c("COL1A1", "DCN", "BGN"),
                B_MZB1_Markers = c("MZB1","IGHG1"))

cellTypeMappings <- list(Myeloid = c(1), 
                         pDC = c(6), # myeloid includes mast
                         Lymphocytes = c(4),
                         Malignant = c(2), 
                         EC = c(5),
                         Fibroblasts = c(3),
                         B_MZB1 = c(7, 8) #cell type omitted in the plot
) 

plotDecontXMarkerPercentage(sce,
    markers = markers,
    groupClusters = cellTypeMappings,
    assayName = "counts")
`

![00001b](https://user-images.githubusercontent.com/63806549/110374968-b85b4080-8027-11eb-982e-bbad8fc5ca9e.png)

I don't know why this behavior it's happening (the B_MZB1 cell type omitted on the horizontal axis of the plot). Anyone can help with this?

obs: I'm separating Plasma B-cells (MZB1+) from lymphocytes because it's clearly on a different cluster, in the case of Follicular B cells (MS4A1+) they cluster together with T and NK cells.

**Comment by joshua-d-campbell** [comment]
Hi @giomaklouf, thanks for pointing this out. I can reproduce the error and will take a look at it shortly. One thing you can do in the meantime is to create your own cluster label where the plasma cells are given the cluster labels you want. Then you can rerun decontX and set the 'z' parameter to your variable that contains cell cluster label. Something like this:

```
newz <- colData(sce)$decontX_clusters
newz[newz == 8] = 7
sce <- decontX(sce, z = newz)
```

**Comment by giomaklouf** [comment]
To use the 'z' parameter was actually pretty good to me since I already had annotations for all the cells (then I was doing duplicated work cause I thought I couldn't put these annotations in advance. My bad.)

In the end you helped me immensely :) Thanks for taking a look at this!

**Comment by joshua-d-campbell** [comment]
This bug has been fixed and is now in the master branch. You can install this version by typing the following:

```
library(devtools)
install_github("campbio/celda")
```

**Comment by HeesooSong** [comment]
I still get the same issue. I installed it recently via Bioconductor btw... is it not updated in Bioconductor version?

**Comment by HeesooSong** [comment]
@joshua-d-campbell  Thanks for the answer. The version of Celda was indeed version 1.6.1 so I checked the version of R and it was 4.0.4 which is quite a recent release I think... But sure I will try to reinstall using github. Is there any command line that you suggest to uninstall Celda stably?

**Comment by joshua-d-campbell** [comment]
Okay, this is an older version of celda. If you upgrade to R 4.2 and reinstall from Bioconductor, it will install the correct version (1.16.0). Or you can try keep your current version of R and install from Github. You should just be able to install from Github and it will install the latest version without needing to uninstall the previous version first.
